version: "3.8"

services:
  mariadb-container:
    image: mariadb:laters
    enviroment: 
      - MARIADB_USER=example-user
    port:
      - 3306:3306
    volumes:
          # <path>
            
services:
  php:
    buidl:
      context:
      dockerfile: dockerfile
    command: php -s 0.0.0.80
    volumos:
      - ""